title: "Dennis Garcia"
baseurl: "/lab"    
url: "https://prcio.github.io"
description: "Dual-Degree Student in Electrical Engineering & Physics | Computational Modeling & Simulations"

remote_theme: riggraz/no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

theme_config:
  appearance: "auto"
  show_description: true
