title: "Dennis Garcia"
description: "Engineering & Physics | Computational Modeling"
baseurl: "/"    
url: "https://prcio.github.io"

remote_theme: riggraz/no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

theme_config:
  appearance: "auto"
  show_description: true
